configuration:
models_ver - insert YOLO version's numbers that the UAP will be trained on.

epsilon, lambda_1, lambda_2 - attack's parameters. more information can be found in the [paper](https://arxiv.org/abs/2205.13618)

BDD_IMG_DIR - a path to the BDD validation set images (or any other wanted dataset)

BDD_LAB_DIR - a path to the BDD validation set labels (or any other wanted dataset)

In [1]:
models_vers = [8] # for example: models_vers = [5] or models_vers = [3, 4, 5]
epsilon = 70
lambda_1 = 1
lambda_2 = 10
seed = 42
patch_size=(640,640)
img_size=(640,640)
batch_size = 8
num_workers = 4
max_labels_per_img = 65
BDD_IMG_DIR = '/Users/coenschoof/miniconda/envs/phantomsponges/BDD100K-to-YOLOV5/bdd_in_YOLOV5_train_newLabels/images/val'
BDD_LAB_DIR = '/Users/coenschoof/miniconda/envs/phantomsponges/BDD100K-to-YOLOV5/bdd_in_YOLOV5_train_newLabels/labels/val'

Load BDD dataset:

In [2]:
import torch
import os
import random
import numpy

from datasets.augmentations1 import train_transform
from datasets.split_data_set_combined import SplitDatasetCombined_BDD

/Users/coenschoof/miniconda/envs/phantomsponges/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# batch = [(1, 'a'), (2, 'b'), (3, 'c')]

# unzipped = zip(*batch)

# numbers, letters = unzipped

# print(numbers)  # Output: (1, 2, 3)
# print(letters)  # Output: ('a', 'b', 'c')

#dus ipv [(tensor, array, string), (tensor, array, string), (tensor, array, string)] hebben we
# train_loader[0] bevat 8 images
# train_loader[1] bevat alle labels per voor 8 images
# train_loader[2] bevat paths naar 8 images
def collate_fn(batch):
    return tuple(zip(*batch))

def set_random_seed(seed_value, use_cuda=True):
    numpy.random.seed(seed_value)  # cpu vars
    torch.manual_seed(seed_value)  # cpu  vars
    random.seed(seed_value)  # Python
    os.environ['PYTHONHASHSEED'] = str(seed_value)  # Python hash buildin
    if use_cuda:
        torch.cuda.manual_seed(seed_value)
        torch.cuda.manual_seed_all(seed_value)  # gpu vars
        torch.backends.cudnn.deterministic = True  # needed
        torch.backends.cudnn.benchmark = False

In [4]:
split_dataset = SplitDatasetCombined_BDD(
            img_dir= BDD_IMG_DIR,
            lab_dir= BDD_LAB_DIR,
            max_lab=max_labels_per_img,
            img_size=img_size,
            transform=train_transform,
            collate_fn=collate_fn)

In [5]:
#train_loader en val_loader 

#train loader bevat een tuple van 3, elk element van de tuple bevat 8 samples (8 samples maakt 1 batch)
#De tuple bestaat uit het volgende:
    #[0] = de image met size (3,640,640)
    #[1] = de bounding boxes met size (x, 5) (5 bestaat uit class, x, y, x, y)
        #lijkt nergens gebruikt te worden
    #[2] = de naam van de image (e.g. 'c98258a4-54a47ff2.jpg')  

    #HEB IK AL DEZE INFORMATIE OOK NODIG WANNEER IK WIL TESTEN OP PASCAL/MTSD? converten is een pain
        #WORDT [2] ERGENS GEBRUIKT? IK WEET DAT [1] NERGENS GEBRUIKT WORDT
train_loader, val_loader, test_loader = split_dataset(val_split=0.1,
                                                      shuffle_dataset=True,
                                                      random_seed=seed,
                                                      batch_size=batch_size,
                                                      ordered=False,
                                                      collate_fn=collate_fn)

In [6]:
import numpy
from attack.uap_phantom_spong_for_yolov8 import UAPPhantomSponge

torch.cuda.empty_cache()

patch_name = r"yolov"
for ver in models_vers:
  patch_name += f"_{ver}"
patch_name += f"_epsilon={epsilon}_lambda1={lambda_1}_lambda2={lambda_2}"

uap_phantom_sponge_attack = UAPPhantomSponge(patch_folder=patch_name, 
                                             train_loader=train_loader, 
                                             val_loader=val_loader, 
                                             epsilon = epsilon, 
                                             lambda_1=lambda_1, 
                                             lambda_2=lambda_2, 
                                             patch_size=patch_size, 
                                             models_vers=models_vers)


CUDA Available:  False


[W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs


In [7]:
adv_img = uap_phantom_sponge_attack.run_attack()

Epoch:  0
saving png of current patch at epoch: 0, batch: 0/169...
66965
TEST
torch.Size([8, 8400])
batch average number (/8) of bbs that will be passed to the NMS stage: 29.375
tensor([0.2500, 0.2500, 0.2500,  ..., 0.2498, 0.2499, 0.2500], grad_fn=<MaximumBackward>)
combined_loss, max_obj, bb_area, iou_loss for this batch =               0.438|0.248|0.019|0.0


KeyboardInterrupt: 

# CODE FOR EVALUATION

In [9]:
import torch
import torch.nn.functional as F
from PIL import Image
import numpy as np
from local_yolos.yolov5.models.experimental import attempt_load
from local_yolos.yolov5.utils.general import non_max_suppression
from torchvision import transforms
from local_yolos.yolov5.utils.metrics import box_iou
from local_yolos.yolov5.utils.plots import Annotator
import time
from tqdm import tqdm

In [10]:
def perturb_img(img_name, change_aspect_ratio = True, output_type = "torch", patch_name = 'final_patch.png'):
    image_path = "/Users/coenschoof/miniconda/envs/phantomsponges/BDD100K-to-YOLOV5/bdd_in_YOLOV5_train_newLabels/images/val/" + img_name
    image = Image.open(image_path)
    image = image.resize((640, 640))
    transform = transforms.Compose([transforms.ToTensor()])
    clean_img = transform(image)

    # Load the image using PIL
    patch_path =  "/Users/coenschoof/miniconda/envs/phantomsponges/PhantomSponges/final_patch.png"
    patch = Image.open(patch_path)
    patch = transform(patch)

    perturbed_img = torch.clamp(clean_img + patch, 0, 1)

    # Assuming you have a torch tensor named torch_image
    # You can resize the tensor to (H, W, C) shape using transpose and multiply by 255 (if it's not already in the correct range)
    #pil_image = transforms.ToPILImage()(result.squeeze().cpu() * 255)
    tensor_min = torch.min(perturbed_img)
    tensor_max = torch.max(perturbed_img)
    normalized_tensor = (perturbed_img - tensor_min) / (tensor_max - tensor_min)

    # Convert the normalized tensor to a PIL image
    pil_image = transforms.ToPILImage()(normalized_tensor.squeeze().cpu())
    if change_aspect_ratio:
        random_scale_w = random.uniform(0.7, 0.9) #1.5, 3
        #random_scale_h = random.uniform(1, 2.5)
        width = int(640 * random_scale_w)
        width = (width // 32) * 32 #ensures that the new width is a multiple of 32, otherwise the model does not work
        height = 640 #height = int(640 * random_scale_h)
        height = (height // 32) * 32
        pil_image = pil_image.resize((width, height))

    if output_type == "torch":
        perturbed_image = transform(pil_image)
    elif output_type == "numpy":
        perturbed_image = np.array(pil_image)
    elif output == "pil":
        pass
    else:
        print("Unsupported output type provided!")

    return(perturbed_image)

In [11]:
image_names = []
for image_np, _, image_name in tqdm(test_loader):
    image_names.append(image_name[0])

100%|██████████| 500/500 [00:08<00:00, 60.14it/s]


# New loss term experiments

In [12]:
#create a tiny batch containing 3 images; 2 random images from the test set, and a fully white image

zeros_tensor = torch.zeros(1, 3, 640, 640)
#zero_output = model(zeros_tensor)[0]

random_index = random.randrange(len(image_names))
other_image = perturb_img(image_names[random_index], change_aspect_ratio = False, output_type = "torch").unsqueeze(0)
random_index = random.randrange(len(image_names))
other_image_2 = perturb_img(image_names[random_index], change_aspect_ratio = False, output_type = "torch").unsqueeze(0)
pil_image = transforms.ToPILImage()(other_image.squeeze())
#display(pil_image)

tiny_batch = torch.cat((other_image, other_image_2, zeros_tensor))
#tiny_batch_output = model(tiny_batch)

In [ ]:
# from local_yolos.yolov8.ultralytics.models.yolo.model import YOLO

# # Load a model
# model = YOLO("yolov8n.pt")

In [ ]:
# results = model(tiny_batch)

In [ ]:
# from attacks_tools.attack_utils import CustomPredictor

In [ ]:
#ONDERSTAANDE OUTPUT MOET NAAR DEZE SHAPE WORDEN OMGEZET

"""Runs Non-Maximum Suppression (NMS) on inference results

Returns:
        list of detections, on (n,6) tensor per image [xyxy, conf, cls]
"""

#output_patch.size() = torch.Size([8, 25200, 85])
    #8 plaatjes per batch
    #25200 bounding boxes per plaatje
    #85 = (x, y, x, y), object confidence score, and class probabilities. (dus 80 class probs)
#print(output_patch.size())

# predictor = CustomPredictor(overrides = dict(model='yolov8n.pt') )
# results = predictor(tiny_batch)

'Runs Non-Maximum Suppression (NMS) on inference results\n\nReturns:\n        list of detections, on (n,6) tensor per image [xyxy, conf, cls]\n'

In [ ]:
# print(type(predictor.model))
# print(type(predictor))
# print(type(predictor.model.zero_grad()))
#print(type(predictor.zero_grad()))

In [ ]:
# predictor(tiny_batch)[0].shape

In [ ]:
# predictor.model(tiny_batch)[0].shape

In [ ]:
# # Assuming you have the original tensor 'results[0]'
# original_tensor = results[0]

# # Create a new tensor with the desired shape 'torch.Size([3, 8400, 85])'
# new_shape = list(original_tensor.shape)
# new_shape[-1] += 1
# new_tensor = torch.zeros(new_shape)

# # Copy the data from the original tensor to the new tensor, shifting values to the right
# new_tensor[:, :, 4] = 1 
# new_tensor[:, :, 0:4], new_tensor[:, :, 5:] = original_tensor[:, :, 0:4], original_tensor[:, :, 4:] 


In [ ]:
# original_tensor[0][0]

In [ ]:
# new_tensor[0][0]

In [ ]:
# x2 = new_tensor[:, :, 5:] * new_tensor[:, :, 4:5]
# conf, _ = x2.max(2, keepdim=False) 
# print(conf.shape)
# target_class = 2
# all_target_conf = x2[:, :, target_class]
# print(all_target_conf.shape)
# under_thr_target_conf = all_target_conf[conf < 0.25]
# print(under_thr_target_conf.shape)

In [ ]:
# new_tensor[0][0]

In [ ]:
# from local_yolos.yolov8.ultralytics.utils.ops import non_max_suppression
# non_max_suppression(results[0])[1].shape

In [13]:
from attacks_tools.attack_utils_2 import CustomPredictor
predictor = CustomPredictor(weights='yolov8n.pt')

YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs


In [17]:
output_patch = predictor(tiny_batch)[0]

In [35]:
x2 = output_patch[:, :, 5:] * output_patch[:, :, 4:5] #torch.Size([8, 25200, 80])     #eq. 2 in paper
#neem per plaatje, per bb, de max confidence.
#We houden dus van 80 bbs 1 class over die de hoogste conf heeft, we slaan de conf scores hier op, niet de bbs of de class
conf, _ = x2.max(2, keepdim=False) #torch.Size([8, 25200])
#neem van alle plaatjes in de batch (8), van alle bounding boxes per plaatje (25200)..
#alleen de bounding box met class "car" (dat is index 2 van de 80)
all_target_conf = x2[:, :, 2] #torch.Size([8, 25200])
under_thr_target_conf = all_target_conf[conf < 0.25]
conf_avg = len(conf.view(-1)[conf.view(-1) > 0.25]) / len(output_patch)
print(f"batch average number (/8) of bbs that will be passed to the NMS stage: {conf_avg}")
zeros = torch.zeros(under_thr_target_conf.size()).to(output_patch.device) #size is rondom torch.Size([200000])
zeros.requires_grad = True

x3 = torch.maximum(0.25 - under_thr_target_conf, zeros) #eq. 3 in paper #size is rondom torch.Size([200000])
#±200000 gedeeld door 201600
print(x3) #BIJNA ALLEMAAL 0.25!!!!!!!
mean_conf = torch.sum(x3, dim=0) / (output_patch.size()[0] * output_patch.size()[1])

batch average number (/8) of bbs that will be passed to the NMS stage: 27.333333333333332
tensor([0.2500, 0.2500, 0.2500,  ..., 0.2500, 0.2500, 0.2500], grad_fn=<MaximumBackward>)


In [38]:
from local_yolos.yolov8.ultralytics.nn.tasks import attempt_load_weights
model = attempt_load_weights('yolov8n.pt',
                                #device=device,
                                inplace=True,
                                #fuse=fuse
                                )

In [47]:
predictor(tiny_batch)[0][0]

tensor([[1.0816e+01, 9.5026e+00, 2.2359e+01,  ..., 3.8697e-07, 2.0936e-07, 2.0073e-07],
        [1.6403e+01, 7.1494e+00, 1.3847e+01,  ..., 3.0834e-07, 2.0266e-07, 2.0283e-07],
        [1.7717e+01, 9.6397e+00, 1.6733e+01,  ..., 2.6557e-07, 1.3718e-07, 1.6254e-07],
        ...,
        [4.6013e+02, 6.2085e+02, 3.5701e+02,  ..., 1.2191e-05, 4.3941e-06, 7.7318e-06],
        [5.9507e+02, 6.1933e+02, 8.8169e+01,  ..., 2.8870e-05, 7.4756e-06, 9.2373e-06],
        [6.0427e+02, 6.1762e+02, 7.1005e+01,  ..., 6.4021e-05, 1.1112e-05, 1.3656e-05]])

In [48]:
model(tiny_batch)[0][0] #DIMENSIES ZIJN GEFLIPT? LIJKT ME NIET DE BEDOELING

tensor([[1.0816e+01, 1.6403e+01, 1.7717e+01,  ..., 4.6013e+02, 5.9507e+02, 6.0427e+02],
        [9.5026e+00, 7.1494e+00, 9.6397e+00,  ..., 6.2085e+02, 6.1933e+02, 6.1762e+02],
        [2.2359e+01, 1.3847e+01, 1.6733e+01,  ..., 3.5701e+02, 8.8169e+01, 7.1005e+01],
        ...,
        [3.8696e-07, 3.0834e-07, 2.6557e-07,  ..., 1.2191e-05, 2.8870e-05, 6.4022e-05],
        [2.0936e-07, 2.0266e-07, 1.3718e-07,  ..., 4.3940e-06, 7.4757e-06, 1.1112e-05],
        [2.0073e-07, 2.0283e-07, 1.6254e-07,  ..., 7.7317e-06, 9.2372e-06, 1.3656e-05]])

In [31]:
x2[0][0].shape

torch.Size([80])

In [ ]:
print(type(predictor.zero_grad()))
print(type(predictor.model))
print(type(predictor))

<class 'NoneType'>
<class 'ultralytics.nn.tasks.DetectionModel'>
<class 'attacks_tools.attack_utils_2.CustomPredictor'>
